#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    May 10, 2026 08:44:09 PM +03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import WS_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Cafe:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("300x500+510+113")
        top.minsize(120, 1)
        top.maxsize(1467, 804)
        top.resizable(1,  1)
        top.title("cafe")
        top.configure(background="#edfefe")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.inq = tk.StringVar()
        self.inq.set('мазани город')

        self.jmay = tk.Button(self.top)
        self.jmay.place(relx=0.2, rely=0.72, height=36, width=177)
        self.jmay.configure(activebackground="#078b8b")
        self.jmay.configure(activeforeground="#2ef3f3")
        self.jmay.configure(background="#76e3f3")
        self.jmay.configure(command=WS_support.Jmay)
        self.jmay.configure(compound='left')
        self.jmay.configure(cursor="fleur")
        self.jmay.configure(disabledforeground="#a3a3a3")
        self.jmay.configure(font="-family {Arial} -size 14")
        self.jmay.configure(foreground="#0a606b")
        self.jmay.configure(highlightbackground="#d9d9d9")
        self.jmay.configure(highlightcolor="#000000")
        self.jmay.configure(text='''ЖМАЙ''')

        self.out = tk.Label(self.top)
        self.out.place(relx=0.2, rely=0.3, height=180, width=180)
        self.out.configure(activebackground="#099f9f")
        self.out.configure(activeforeground="#099f9f")
        self.out.configure(anchor='w')
        self.out.configure(background="#a9fafa")
        self.out.configure(compound='left')
        self.out.configure(cursor="fleur")
        self.out.configure(disabledforeground="#a3a3a3")
        self.out.configure(font="-family {Arial} -size 10")
        self.out.configure(foreground="#0a606b")
        self.out.configure(highlightbackground="#d9d9d9")
        self.out.configure(highlightcolor="#000000")
        self.out.configure(relief="sunken")
        self.out.configure(wraplength="179")

        self.inv = tk.Entry(self.top)
        self.inv.place(relx=0.2, rely=0.16, height=40, relwidth=0.6)
        self.inv.configure(background="#b5fbfb")
        self.inv.configure(cursor="fleur")
        self.inv.configure(disabledforeground="#a3a3a3")
        self.inv.configure(exportselection="0")
        self.inv.configure(font="-family {Arial} -size 14")
        self.inv.configure(foreground="#0a606b")
        self.inv.configure(highlightbackground="#d9d9d9")
        self.inv.configure(highlightcolor="#000000")
        self.inv.configure(insertbackground="#000000")
        self.inv.configure(justify='center')
        self.inv.configure(selectbackground="#d9d9d9")
        self.inv.configure(selectforeground="black")
        self.inv.configure(textvariable=self.inq)

def start_up():
    WS_support.main()

if __name__ == '__main__':
    WS_support.main()




