#############################################################################
# Generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#  May 10, 2026 08:48:29 PM +03  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


#######  Default Fonts ########
set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkTooltipFont
set vTcl(actual_gui_font_tooltip_name)  TkTooltipFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) Relative
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -relief flat -background #edfefe -container 0 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 300x500+510+113
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1467 804
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "cafe"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Cafe" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label "$top.lab51" \
        -activebackground #099f9f -activeforeground #099f9f -anchor w \
        -background #a9fafa -borderwidth 2 -compound left -cursor fleur \
        -disabledforeground #a3a3a3 -font "-family {Arial} -size 14" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief sunken -state normal -takefocus 0 -underline -1 \
        -width 180 -wraplength 179 
    vTcl:DefineAlias "$top.lab51" "out" vTcl:WidgetProc "Cafe" 1
    button "$top.but50" \
        -activebackground #078b8b -activeforeground #2ef3f3 -anchor center \
        -background #76e3f3 -borderwidth 2 -command "Jmay" -compound left \
        -cursor fleur -default disabled -disabledforeground #a3a3a3 \
        -font "-family {Arial} -size 14" -foreground #0a606b -height 36 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "ЖМАЙ" \
        -underline -1 -width 177 -wraplength 0 
    vTcl:DefineAlias "$top.but50" "jmay" vTcl:WidgetProc "Cafe" 1
    entry "$top.ent49" \
        -background #b5fbfb -borderwidth 1 -cursor fleur \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {Arial} -size 14" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify center \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -textvariable "inq" \
        -validate none -width 214 
    vTcl:DefineAlias "$top.ent49" "inv" vTcl:WidgetProc "Cafe" 1
    ###################
    # SETTING GEOMETRY
    ###################
# add p1 basename = $top.lab51
    place $top.lab51 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.3 -width 0 -relwidth 0.6 \
        -height 0 -relheight 0.36 -anchor nw -bordermode ignore 
# add p1 basename = $top.but50
    place $top.but50 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.72 -width 177 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $top.ent49
    place $top.ent49 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.16 -width 180 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

