#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    May 10, 2026 08:08:18 PM +03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import requests

API_KEY = '0bfeda0cafe37e0e56e604480d037baf'

import WS

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = WS.Cafe(_top1)
    root.mainloop()

def Jmay(*args):
    city = _w1.inv.get().strip()

    if not city:
        _w1.out.configure(text="Пожалуйста, введите город.")
        return
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric&lang=ru"
    try:
        response = requests.get(url)
        data = response.json()


        if data.get("cod") != 200:
            _w1.out.configure(text="Город не найден.")
            return

        temp = data["main"]["temp"]
        feels_like = data["main"]["feels_like"]
        description = data["weather"][0]["description"]

        result_text = (
            f"Погода в городе: {city.title()}\n"
            f"Температура: {temp}°C (ощущается как {feels_like}°C)\n"
            f"На улице: {description.capitalize()}"
        )

        _w1.out.configure(text=result_text)

    except requests.exceptions.RequestException:
        _w1.out.configure(text="Ошибка соединения с интернетом.")

    if _debug:
        print('WS_support.Jmay')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

if __name__ == '__main__':
    WS.start_up()




