# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qwerty.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(600, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(600, 1000))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.jmay = QtWidgets.QPushButton(self.centralwidget)
        self.jmay.setGeometry(QtCore.QRect(135, 847, 330, 100))
        self.jmay.setAutoFillBackground(False)
        self.jmay.setStyleSheet("QPushButton {\n"
"    border-image: url(wd.png) 0 0 0 0 stretch stretch;\n"
"    border: none;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-image: url(wd1.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"")
        self.jmay.setText("")
        self.jmay.setObjectName("jmay")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -273, 600, 1611))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Gemini_Generated_Image_exl93nexl93nexl9.png"))
        self.label.setObjectName("label")
        self.INV = QtWidgets.QLineEdit(self.centralwidget)
        self.INV.setGeometry(QtCore.QRect(60, 413, 480, 90))
        font = QtGui.QFont()
        font.setFamily("Digiface")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.INV.setFont(font)
        self.INV.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.INV.setStyleSheet("border-image: url(wqw.png) 0 0 0 0 stretch stretch;")
        self.INV.setText("")
        self.INV.setAlignment(QtCore.Qt.AlignCenter)
        self.INV.setObjectName("INV")
        self.inmon = QtWidgets.QLineEdit(self.centralwidget)
        self.inmon.setGeometry(QtCore.QRect(60, 525, 480, 90))
        font = QtGui.QFont()
        font.setFamily("Digiface")
        font.setPointSize(28)
        self.inmon.setFont(font)
        self.inmon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inmon.setStyleSheet("border-image: url(wqw.png) 0 0 0 0 stretch stretch;")
        self.inmon.setText("")
        self.inmon.setAlignment(QtCore.Qt.AlignCenter)
        self.inmon.setObjectName("inmon")
        self.outv = QtWidgets.QLineEdit(self.centralwidget)
        self.outv.setGeometry(QtCore.QRect(60, 637, 480, 90))
        font = QtGui.QFont()
        font.setFamily("Digiface")
        font.setPointSize(28)
        self.outv.setFont(font)
        self.outv.setStyleSheet("border-image: url(wqw.png) 0 0 0 0 stretch stretch;")
        self.outv.setAlignment(QtCore.Qt.AlignCenter)
        self.outv.setObjectName("outv")
        self.outmon = QtWidgets.QLineEdit(self.centralwidget)
        self.outmon.setGeometry(QtCore.QRect(60, 749, 480, 90))
        font = QtGui.QFont()
        font.setFamily("Digiface")
        font.setPointSize(28)
        self.outmon.setFont(font)
        self.outmon.setStyleSheet("border-image: url(wqw.png) 0 0 0 0 stretch stretch;")
        self.outmon.setAlignment(QtCore.Qt.AlignCenter)
        self.outmon.setObjectName("outmon")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(225, 70, 150, 150))
        self.label_2.setStyleSheet("border-image: url(WEWEW.png) 0 0 0 0 stretch stretch;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 262, 480, 50))
        font = QtGui.QFont()
        font.setFamily("Digiface")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label.raise_()
        self.jmay.raise_()
        self.INV.raise_()
        self.inmon.raise_()
        self.outv.raise_()
        self.outmon.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "КОНВЕРТАТОР ВАЛЮТ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
