# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wisper.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 811)
        MainWindow.setStyleSheet("background = rgb(170, 170, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tv = QtWidgets.QTextEdit(self.centralwidget)
        self.tv.setGeometry(QtCore.QRect(21, 21, 554, 358))
        self.tv.setReadOnly(True)
        self.tv.setObjectName("tv")
        self.jmayv = QtWidgets.QPushButton(self.centralwidget)
        self.jmayv.setGeometry(QtCore.QRect(476, 427, 99, 71))
        font = QtGui.QFont()
        font.setFamily("GOST type A")
        font.setPointSize(18)
        self.jmayv.setFont(font)
        self.jmayv.setObjectName("jmayv")
        self.inv = QtWidgets.QLineEdit(self.centralwidget)
        self.inv.setGeometry(QtCore.QRect(21, 427, 442, 71))
        self.inv.setText("")
        self.inv.setObjectName("inv")
        self.outv = QtWidgets.QLineEdit(self.centralwidget)
        self.outv.setGeometry(QtCore.QRect(21, 532, 442, 71))
        self.outv.setText("")
        self.outv.setObjectName("outv")
        self.jmayo = QtWidgets.QPushButton(self.centralwidget)
        self.jmayo.setGeometry(QtCore.QRect(476, 532, 99, 71))
        font = QtGui.QFont()
        font.setFamily("GOST type A")
        font.setPointSize(18)
        self.jmayo.setFont(font)
        self.jmayo.setObjectName("jmayo")
        self.jmay = QtWidgets.QPushButton(self.centralwidget)
        self.jmay.setGeometry(QtCore.QRect(21, 651, 554, 78))
        font = QtGui.QFont()
        font.setFamily("GOST type A")
        font.setPointSize(18)
        self.jmay.setFont(font)
        self.jmay.setObjectName("jmay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.jmayv.setText(_translate("MainWindow", "обзор"))
        self.jmayo.setText(_translate("MainWindow", "обзор"))
        self.jmay.setText(_translate("MainWindow", "Жмай"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
