#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    May 15, 2026 12:40:59 AM +03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import er

muma=["Ванильное", "Шоколадное", "Клубничное", "Фисташковое"]
b=0
n=1
v=""

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = er.caef_ice(_top1)

    _w1.sirt.set("сорт")
    _w1.tep.set("тип")
    _w1.rf.set("изменить")

    z=", ".join(muma)

    _w1.tv.delete("1.0", END)
    _w1.tv.insert("1.0", f"конфигуратор мороженного \n сорта: {z} \n типы: мягкое, эскимо")

    sort=_w1.men54_m
    sort.delete(0, END)
    for items in muma:
        sort.add_command(label=items,command=lambda x=items: s(x))
    root.mainloop()

def dob(*args):
    if _debug:
        print('er_support.dob')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
        _w1.rf.set("добавить")

def s(k):
    _w1.sirt.set(k)

def esk(*args):
    if _debug:
        print('er_support.esk')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
        _w1.tep.set("эскимо")

def mmor(*args):
    if _debug:
        print('er_support.mmor')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
        _w1.tv.delete(1.0, "end")
        _w1.tv.insert("end",f"вот {_w1.tep.get()} {_w1.sirt.get()} и не чего ждать тут два часа")
def myag(*args):
    if _debug:
        print('er_support.myag')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
        _w1.tep.set("мягкое")

def prim(*args):
    if _debug:
        print('er_support.prim')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
        c=_w1.vvod.get().strip()
        if _w1.rf.get()=="удалить":
            if not(c in muma):
                _w1.tv.insert("end",f"чумба, {c} такого не ма")
            elif c in muma:
                muma.remove(c)
                sort = _w1.men54_m
                sort.delete(0, END)
                for items in muma:
                    sort.add_command(label=items, command=lambda x=items: s(x))
                z = ", ".join(muma)
                _w1.tv.delete(1.0, "end")
                _w1.tv.insert("end", "всё чисто")
                _w1.tv.delete(1.0, "end")
                _w1.tv.insert("1.0", f"конфигуратор мороженного \n сорта: {z} \n типы: мягкое, эскимо")
        elif _w1.rf.get()=="добавить":
            if c in muma:
                _w1.tv.insert("end", f"чумба {c} и так тут")
            elif not (c in muma):
                muma.append(c)
                sort = _w1.men54_m
                sort.delete(0, END)
                for items in muma:
                    sort.add_command(label=items, command=lambda x=items: s(x))
                z = ", ".join(muma)
                _w1.tv.delete(1.0, "end")
                _w1.tv.insert("end", f"всё {c} це как родной залетел")
                _w1.tv.delete(1.0, "end")
                _w1.tv.insert("1.0", f"конфигуратор мороженного \n сорта: {z} \n типы: мягкое, эскимо")

def dobb(*args):
    if _debug:
        print('er_support.dobb')
        for arg in args:
            print ('	another arg:', arg)
        sys.stdout.flush()
def yd(*args):
    if _debug:
        print('er_support.yd')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
        _w1.rf.set("удалить")

if __name__ == '__main__':
    er.start_up()




