#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    May 10, 2026 09:21:03 PM +03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import requests
import wd

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = wd.Toplevel1(_top1)
    root.mainloop()

def jmay(*args):
    city=_w1.inv.get().strip()
    _w1.out.delete('1.0', tk.END)

    if not city:
        _w1.out.insert(tk.END, "город мазани")
        return

    url = "https://ru.wikipedia.org/w/api.php"
    params = {
        "action": "query",
        "prop":"extracts",
        "format": "json",
        "titles": city,
        "explaintext": True,
        "exintro": True
    }
    headers = {
        "User-Agent": "matumba"
    }
    try:
        response=requests.get(url,params=params,headers=headers)
        deta=response.json()
        pages=deta["query"]["pages"]
        page_id=list(pages.keys())[0]
        if page_id == "-1":
            _w1.out.insert(tk.END, f"инфа ({city}) не найдена")

            return

        extract=pages[page_id]["extract"]

        if not extract:
            _w1.out.insert(tk.END, "Статья найдена, но описание отсутствует.")

            return

        sentences = extract.split(". ")
        short_facts= ". ".join(sentences[:3]) + "."
        result_text=f"{city.title()}:\n\n{short_facts}"
        _w1.out.insert(tk.END, result_text)

    except requests.exceptions.RequestException:
        _w1.out.insert(tk.END, "Ошибка соединения с интернетом.")
    except Exception as e:
        _w1.out.insert(tk.END, f"Произошла ошибка: {e}")

    if _debug:
        print('wd_support.jmay')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

if __name__ == '__main__':
    wd.start_up()